#pragma once

const char* WIFI_PRIMARY_SSID = "YOUR_WIFI_NAME";
const char* WIFI_PRIMARY_PASSWORD = "YOUR_WIFI_PASSWORD";

const char* WIFI_FALLBACK_SSID = "YOUR_WIFI_NAME";
const char* WIFI_FALLBACK_PASSWORD = "YOUR_WIFI_PASSWORD";